services:
  app:
    build: ./app
    container_name: studylink_app
    restart: always
    networks:
      - mynetwork
    volumes:
      - ./app:/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  web:
    image: nginx:latest
    container_name: studylink_nginx_server
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/app
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - mynetwork
    depends_on:
      - app

  db:
    image: mysql:latest
    container_name: studylink_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studylink
    volumes:
      - db_data:/var/lib/mysql
      - ./db/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/iscte_courses_units.csv:/docker-entrypoint-initdb.d/db/iscte_courses_units.csv
    command: --secure-file-priv=""
    ports:
      - "3307:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
