CREATE DATABASE IF NOT EXISTS studylink;
USE studylink;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS user_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,  
    profile_pic VARCHAR(255) DEFAULT '/static/uploads/ProfilePics/default.jpg',
    bio TEXT,
    class_year INT DEFAULT NULL,
    course VARCHAR(255) DEFAULT '',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS curricular_units (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS user_subjects (
    user_id INT NOT NULL,
    subject_id INT NOT NULL,
    PRIMARY KEY (user_id, subject_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES curricular_units(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS contacto (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    mensagem TEXT NOT NULL,
    data TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO curricular_units (name) VALUES
('Algoritmia e Estrutura de Dados'),
('Fundamentos de Programação'),
('Trabalho, Organizações e Tecnologia'),
('Planeamento e Gestão de Projetos'),
('Estatística e Probabilidades'),
('Complementos de Matemática Aplicada'),
('Matemática Aplicada'),
('Fundamentos de Análise de Dados'),
('Inteligência Artificial'),
('Apresentações em Público com Técnicas Teatrais'),
('Introdução ao Design Thinking'),
('Trabalho Académico com Inteligência Artificial'),
('Programação Orientada para Objectos'),
('Empreendedorismo e Inovação I'),
('Empreendedorismo e Inovação II'),
('Projetos em Ambientes Web e Cloud'),
('Programação e Análise de Dados em Excel'),
('Aprendizagem Automática Não Supervisionada'),
('Aprendizagem Automática Supervisionada'),
('Sistemas de Informação Analíticos'),
('Bases de Dados e Gestão de Informação'),
('Agentes Autónomos'),
('Algoritmos Avançados de Procura'),
('Projeto Aplicado de Inteligência Artificial II'),
('Projeto Aplicado de Inteligência Artificial I'),
('Big Data'),
('Tecnologia, Economia e Sociedade'),
('Text Mining'),
('Sistemas Operativos e Virtualização'),
('Introdução às Redes de Computadores'),
('Introdução à Cibersegurança'),
('Bases de Dados e Segurança'),
('Programação para a Internet'),
('Segurança em Redes de Computadores'),
('Criptografia Aplicada'),
('Análise Forense Digital'),
('Sistemas Distribuídos e Segurança'),
('Ética e Legislação em Cibersegurança'),
('Projeto Aplicado de Tecnologias Digitais e Segurança de Informação I'),
('Segurança de Software e Aplicacional'),
('Projeto Aplicado de Tecnologias Digitais e Segurança de Informação II'),
('Auditoria de Segurança em Sistemas e Redes Digitais'),
('Operações de Segurança e Gestão de Incidentes'),
('Desenho Centrado no Utilizador'),
('Desenvolvimento Ágil de Software'),
('Desenvolvimento de Software para A Nuvem'),
('Programação para Ciência dos Dados'),
('Projeto Aplicado de Software e Aplicações I'),
('Projeto Aplicado de Software e Aplicações II'),
('Programação para Mobilidade'),
('Álgebra Linear e Aplicações'),
('Cálculo A uma Variável'),
('Cálculo A Múltiplas Variáveis'),
('Álgebra Linear Numérica'),
('Otimização Matemática'),
('Análise Numérica'),
('Grafos e Redes Complexas'),
('Modelação Financeira'),
('Introdução à Estatística e Probabilidades'),
('Tomada de Decisão Apoiada em Dados'),
('Matemática Computacional'),
('Processos Estocásticos e Simulação'),
('Projeto de Matemática Aplicada II'),
('Projeto de Matemática Aplicada I'),
('Fundamentos de Automação'),
('Projeto Aplicado de Automação II'),
('Interação Pessoa-Máquina e Simulação'),
('Redes Industriais e Supervisão'),
('Projeto Aplicado de Automação I'),
('Gestão de Pessoas na Era Digital'),
('Aplicações de Sistemas de Informação para a Gestão'),
('Fundamentos de Gestão'),
('Logística no Comércio e na Indústria'),
('Estratégia, Planeamento e Orçamentação'),
('Gestão de Riscos na Era Digital'),
('Métodos Analíticos Aplicados à Gestão'),
('Gestão Fiscal'),
('Gestão Comercial, Vendas na Era Digital'),
('Enquadramento Legal das Pessoas Coletivas'),
('Gestão de Investimentos'),
('Monitorizar A Performance da Gestão'),
('Finanças Empresariais e Gestão de Tesouraria'),
('Empreendedorismo e Inovação III'),
('Marketing Digital'),
('Relatório Integrado'),
('Sistema de Saúde'),
('Noções de Saúde Humana'),
('Psicologia Social da Saúde'),
('Gestão de Organizações de Saúde'),
('Dados de Saúde'),
('Sistemas de Informação em Saúde'),
('Logística Digital em Contexto Hospitalar'),
('Tecnologias Assistivas e Tele-Saúde'),
('Inteligência Artificial na Saúde'),
('Recursos Digitais Estáticos'),
('Metodologias de Ensino e Aprendizagem'),
('Geometria e Estatística'),
('Psicologia da Aprendizagem'),
('Comunicação e Aprendizagem Multimédia'),
('Recursos Digitais Dinâmicos'),
('Desenvolvimento Curricular'),
('Ambientes Virtuais de Aprendizagem'),
('Gestão da Formação'),
('Inclusão e Acessibilidade'),
('Projeto Aplicado de Tecnologias Digitais Educativas I'),
('Projeto Aplicado de Tecnologias Digitais Educativas II'),
('Ciência de Materiais'),
('Introdução ao Ambiente Construído'),
('Projeto I'),
('Modelação da Informação de Construção I'),
('Sistemas e Processos de Construção de Edifícios I'),
('Qualidade e Segurança na Construção'),
('Técnicas de Levantamento, Diagnóstico e Reabilitação de Edifícios'),
('Modelação da Informação de Construção II'),
('Projeto II'),
('Projeto III'),
('Modelação da Informação de Construção'),
('Sistemas, Instalações e Edifícios Inteligentes'),
('Sistemas e Processos de Construção de Edifícios II'),
('Gestão da Construção'),
('Projeto IV'),
('Projeto V'),
('Metodologia BIM'),
('Edifícios e Construção Sustentáveis');
;
